# Generated by Django 2.2.6 on 2019-10-05 05:57

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zones',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('geo_ref', models.CharField(max_length=8)),
                ('state', models.IntegerField()),
                ('geo_type', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'zones',
            },
        ),
    ]
