# Generated by Django 2.2.6 on 2019-10-06 16:46

import api.models
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoRef',
            fields=[
                ('code', models.CharField(editable=False, max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('_id', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name': 'Referencia Geografica',
                'verbose_name_plural': 'Referencias Geograficas',
                'db_table': 'geo_ref',
            },
        ),
        migrations.CreateModel(
            name='Zones',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('state', models.IntegerField()),
                ('geo_type', models.CharField(max_length=5)),
                ('coordinates', djongo.models.fields.ArrayModelField(model_container=api.models.CoordinateZone)),
                ('geo_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.GeoRef')),
            ],
            options={
                'verbose_name': 'Zona',
                'db_table': 'zones',
            },
        ),
        migrations.CreateModel(
            name='CommentsZone',
            fields=[
                ('date', models.DateTimeField(auto_created=True)),
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('txt', models.TextField()),
                ('user', models.CharField(max_length=100)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Zones')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'db_table': 'zones_comments',
            },
        ),
    ]
