# Generated by Django 2.2.6 on 2019-10-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zones',
            options={'ordering': ['name'], 'verbose_name': 'Zona'},
        ),
        migrations.AlterField(
            model_name='dangerrangezone',
            name='code_danger',
            field=models.IntegerField(choices=[(1, 'Nivel 1 - Todo para ir bien'), (2, 'Nivel 2 - Conduzcase con cuidado'), (3, 'Nivel 3 - Mantengase alerta'), (4, 'Nivel 4 - Si puede evite la zona'), (5, 'Nivel 5 - No ingrese a la zona')], default=1, verbose_name='Nivel'),
        ),
    ]
